---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
spec:
  targetNamespaces:
  - ripsaw
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ripsaw
spec:
  channel: alpha
  name: ripsaw
  source: operatorhubio-catalog
  sourceNamespace: olm