apiVersion: v1
data:
  configManagementPlugins: |
    - generate:
        args:
        - helm template . > all.yaml && kustomize build
        command:
        - sh
        - -c
      init:
        args:
        - helm init --client-only && helm dependency build
        command:
        - /bin/sh
        - -c
      name: kustomized-helm
  helm.repositories: |-
    - url: https://helm.goharbor.io
      name: harbor
    - url: https://strimzi.io/charts/
      name: strimzi
    - url: http://storage.googleapis.com/kubernetes-charts-incubator
      name: incubator
    - url: https://charts.bitnami.com
      name: bitnami
    - url: https://charts.rook.io/release
      name: rook-release
  repositories: |
    - url: https://github.com/niiku/wheel-cluster-config.git
  resource.customizations: |
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreDifferences: |
        jsonPointers:
        - /spec/additionalPrinterColumns/0/priority
        - /spec/additionalPrinterColumns/1/priority
        - /status/lastVersion
    build.openshift.io/BuildConfig:
      ignoreDifferences: |
        jsonPointers:
        - /status
#    "/Secret":
#      ignoreDifferences: |
#        jsonPointers:
#        - /metadata/labels
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - "Secrets"
      clusters:
      - https://kubernetes.default.svc
  dex.config: |-
    connectors:
      - type: oidc
        id: google
        name: Google
        config:
          issuer: https://accounts.google.com
          clientID: $dex.google.clientID
          clientSecret: $dex.google.clientSecret
          hostedDomains:
          - nikio.io
  url: https://argocd.wheel.sh
kind: ConfigMap
metadata:
  name: argocd-cm
