apiVersion: v1
data:
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    g, nikio:wheel, role:org-admin
    g, admin@nikio.io, role:org-admin
  policy.default: 'role:readonly'
  scopes: '[cognito:groups, email]'
kind: ConfigMap
metadata:
  name: argocd-rbac-cm