apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence-server
  labels:
    app: confluence
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: confluence
  template:
    metadata:
      labels:
        app: confluence
        component: server
    spec:
      securityContext:
        fsGroup: 2002
      containers:
        - name: confluence
          image: "atlassian/confluence-server:6.15.7"
          imagePullPolicy: IfNotPresent
          env:
            - name: CATALINA_CONNECTOR_PROXYNAME
              value: "docs.wheel.sh"
            - name: CATALINA_CONNECTOR_PROXYPORT
              value: "443"
            - name: CATALINA_CONNECTOR_SCHEME
              value: "https"
            - name: CATALINA_CONNECTOR_SECURE
              value: "true"
            - name: JVM_MINIMUM_MEMORY
              value: "1024m"
            - name: JVM_MAXIMUM_MEMORY
              value: "1024m"
            - name: JVM_SUPPORT_RECOMMENDED_ARGS
              value: "-XX:MaxMetaspaceSize=512m -XX:MaxDirectMemorySize=10m  -Dsynchrony.memory.max=0m"
          securityContext:
            runAsUser: 0
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
            - name: synchrony
              containerPort: 8091
              protocol: TCP
#          livenessProbe:
#            tcpSocket:
#              port: http
#            initialDelaySeconds: 60
#            periodSeconds: 15
#            timeoutSeconds: 3
#          readinessProbe:
#            tcpSocket:
#              port: http
#            initialDelaySeconds: 30
#            periodSeconds: 15
#            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /var/atlassian/application-data/confluence
              name: data
            - mountPath: /opt/atlassian/confluence/work
              name: temp
            - mountPath: /opt/atlassian/confluence/temp
              name: temp
            - mountPath: /opt/atlassian/confluence/logs
              name: temp
          resources:
            {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: confluence-data
        - name: entrypoint
          configMap:
            name: entrypoint
            defaultMode: 0554
        - name: temp
          emptyDir: {}
