apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 10m
  labels:
    app: confluence
    component: server
  name: confluence
spec:
  host: docs.wheel.sh
  path: /
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: confluence
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - routerName: router
