apiVersion: v1
kind: Service
metadata:
  name: confluence
  labels:
    app: confluence
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 8091
      targetPort: synchrony
      protocol: TCP
      name: synchrony
  selector:
    app: confluence
    component: server
