---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault
  namespace: vault
spec:
  channel: beta
  name: vault
  source: operatorhubio-catalog
  sourceNamespace: olm