apiVersion: v1
kind: Service
metadata:
  labels:
    app: guacamole
  name: guacamole
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: proxy-tls
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: guacamole
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}