mysql:
  securityContext:
    enabled: true
    fsGroup: 1000230000
    runAsUser: 1000230000
  root:
    existingSecret: guacamole-mysql
  db:
    user: guacamole
  replication:
    enabled: false
  master:    
    persistence:
      size: 1Gi
      storageClass: "glusterfs-storage"