apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
spec:
  targetNamespaces:
  - falco-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: falco
spec:
  channel: stable
  name: falco
  source: operatorhubio-catalog
  sourceNamespace: olm  