apiVersion: falco.org/v1alpha1
kind: Falco
metadata:
  name: falco-with-ebpf
spec:
  ebpf:
    enabled: true
  resources:
   requests:
     cpu: 50m
     memory: 64Mi
  serviceAccount:
    name: falco
