apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nikio
  name: nikio
spec:
  host: stage.nikio.io
  path: /
  port:
    targetPort: proxy
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: Reencrypt
  to:
    kind: Service
    name: proxy
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - routerName: router