apiVersion: v1
kind: Service
metadata:
  labels:
    app: nikio
  name: nikio
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: nikio
  sessionAffinity: None
  type: ClusterIP