---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
spec:
  targetNamespaces:
  - rook-ceph
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rook-ceph
  namespace: rook-ceph-operator
spec:
  channel: beta
  name: rook-ceph
  source: operatorhubio-catalog
  sourceNamespace: olm