apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: logspout
  name: logspout
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: logspout
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: logspout
    spec:
      containers:
        - env:
            - name: SYSLOG_TAG
              value: >-
                {{ index .Container.Config.Labels "io.kubernetes.pod.namespace"
                }}[{{ index .Container.Config.Labels "io.kubernetes.pod.name"
                }}]
            - name: SYSLOG_HOSTNAME
              value: >-
                {{ index .Container.Config.Labels "io.kubernetes.container.name"
                }}
            - name: SYSLOG_STRUCTURED_DATA
              valueFrom:
                secretKeyRef:
                  key: syslog-structured-data
                  name: logspout-config
            - name: ROUTE_URIS
              value: 'syslog+tcp://logs-01.loggly.com:514'
          image: 'gliderlabs/logspout:v3.2.4'
          imagePullPolicy: IfNotPresent
          name: logspout
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 16Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /var/run/docker.sock
            type: ''
          name: log
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
