
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
spec:
  targetNamespaces:
  - eclipse-che
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: postgres-operator
spec:
  channel: stable
  name: postgres-operator
  source: operatorhubio-catalog
  sourceNamespace: olm