---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
spec:
  targetNamespaces:
  - jaeger-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger
spec:
  channel: alpha
  name: jaeger
  source: operatorhubio-catalog
  sourceNamespace: olm