
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
spec:
  targetNamespaces:
  - wildfly-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: wildfly
spec:
  channel: alpha
  name: wildfly
  source: operatorhubio-catalog
  sourceNamespace: olm