  # Default values for strimzi-kafka-operator.
strimzi-kafka-operator:
  watchNamespaces:
  - playground

# Override the docker image repository used by all Strimzi images
  # imageRepositoryOverride: foobar
  # Override the docker image tag used by all Strimzi images
  # imageTagOverride: latest
  createGlobalResources: true
  resources:
    limits:
      memory: 256Mi
      cpu: 1
    requests:
      memory: 128Mi
      cpu: 50m
