argocdNamespace: argocd
server: https://kubernetes.default.svc
project: default
requestor: admin@nikio.io
applications:
  - name: apps
    namespace: argocd
    noNamespaceCreation: true
    helm:
      valueFiles:
        - "values.yaml"
    path: apps
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  - name: argocd
    namespace: argocd
    path: argocd
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  - name: sealed-secrets
    helm:
      valueFiles:
        - "values.yaml"
    path: sealed-secrets
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  - name: confluence
    path: confluence
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  # - name: olm
  #   path: olm
  #   repoURL: https://github.com/niiku/wheel-cluster-config.git
  #   targetRevision: HEAD
  #   syncPolicy:
  #     automated:
  #       prune: true
  # - name: eclipse-che
  #   path: eclipse-che
  #   repoURL: https://github.com/niiku/wheel-cluster-config.git
  #   targetRevision: HEAD
  #   syncPolicy:
  #     automated:
  #       prune: true
  - name: strimzi
    helm:
      valueFiles:
        - "values.yaml"
    path: strimzi
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
