argocdNamespace: argocd
server: https://kubernetes.default.svc
project: default
requestor: admin@nikio.io
applications:
  - name: apps
    namespace: argocd
    noNamespaceCreation: true
    helm:
      valueFiles:
        - "values.yaml"
    path: apps
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  - name: argocd
    namespace: argocd
    path: argocd
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  - name: sealed-secrets
    helm:
      valueFiles:
        - "values.yaml"
    path: sealed-secrets
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  - name: confluence
    path: confluence
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  - name: nikio
    path: nikio
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  - name: nikio-stage
    path: nikio-stage
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  - name: build
    path: build
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    ignoreDifferences:
      - group: build.openshift.io
        kind: BuildConfigs
        name: "*"
        jsonPointers:
          - /status
    syncPolicy:
      automated:
        prune: true
  - name: minio
    path: minio
    enabled: false
    helm:
      valueFiles:
        - "values.yaml"
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  - name: guacamole
    path: guacamole
    helm:
      valueFiles:
        - "values.yaml"
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
  - name: loggly
    path: loggly
    nodeSelector: ""
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
    ignoreDifferences:
      - group: security.openshift.io
        kind: SecurityContextConstraints
        name: "loggly"
        jsonPointers:
          - /requiredDropCapabilities
          - /defaultAddCapabilities
  - name: nfs
    path: nfs
    helm:
      valueFiles:
        - "values.yaml"
    repoURL: https://github.com/niiku/wheel-cluster-config.git
    targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
