kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che-operator
subjects:
  - kind: ServiceAccount
    name: che-operator
    namespace: eclipse-che
roleRef:
  kind: ClusterRole
  name: che-operator
  apiGroup: rbac.authorization.k8s.io