apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-operator
  template:
    metadata:
      labels:
        app: che-operator
    spec:
      containers:
        - name: che-operator
          image: quay.io/eclipse/che-operator:nightly
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - /usr/local/bin/che-operator
          imagePullPolicy: Always
          #          TODO: to be uncommented when issue
          #          https://github.com/operator-framework/operator-sdk/issues/1234
          #          is fixed
          #          readinessProbe:
          #            exec:
          #              command:
          #                - stat
          #                - /tmp/operator-sdk-ready
          #            initialDelaySeconds: 4
          #            periodSeconds: 10
          #            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "che-operator"
      restartPolicy: Always
      serviceAccountName: che-operator
      terminationGracePeriodSeconds: 5