---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: eclipse-che
spec:
  targetNamespaces:
  - eclipse-che
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: eclipse-che
  namespace: eclipse-che
spec:
  channel: stable
  name: eclipse-che
  source: operatorhubio-catalog
  sourceNamespace: olm