apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eclipse-che-edit
  namespace: eclipse-che
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: che-operator
    namespace: eclipse-che
